embedding:
    chroma_persist_dir: chroma_db
    openAI_embedding_model: text-embedding-3-small # allowed values: "text-embedding-3-small", "text-embedding-3-large" , ...(further openAI modesl)
    max_chunk_size: 8000 # max tokens per chunk
    chunk_overlap: 800 # overlap tokens between chunks
    top_n_entries: 3
system_documentation:
    source_folder: system_documentation # possible values: "system_documentation_copy", "system_documentation"
test_cases:
    source_folder: test_cases_copy # possible values: "test_cases_copy", "test_cases"
llm:
    provider: openAI # allowed values: "openAI", "xai"
    openAI_model: gpt-5 # should not be changed
    xai_model: grok-4 # should not be changed

process_orchestration:
    update_chroma_db: False # True/False
    run_test_cases: False # True/False
    run_evaluation: True # True/False
    rag_framework: RAG  # allowed values: "RAG", "Self-RAG", "CoRAG"
    knowledge_basis: all # allowed values: "all", "DB", "API"

evaluation:
    test_case_folder: 20250830_173933_RAG_openAI_all
